image: openjdk:8-jdk

variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"
  
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/TickDynamic-*.jar"
  ARTIFACTS: "$CI_PROJECT_DIR/TickDynamic-*.jar"

cache:
 paths:
 - $CACHE_DIR
 - $CACHE_DIR2
 key: "$CI_BUILD_REF_NAME"
 untracked: false

stages:
- deploy
    
deploy:
  stage: deploy
  script:
  - ./gradlew clean
  - ./gradlew build curseforge uploadToModsIO -PcurseForgeApiKey=$curseForgeApiKey -PmodsioApiKey=$modsioApiKey --stacktrace --continue
  - cp $ORIG_ARTIFACTS .
  when: manual
  artifacts:
    name: "TickDynamic-1.12.2-$(cat $CACHE_DIR/.version)"
    paths:
    - $ARTIFACTS
    
deployMaven:
  stage: deploy
  script:
  - ./gradlew clean
  - ./gradlew build uploadArchives curseforge uploadToModsIO -PksAlias=$ksAlias -Pks=$ks -PksPass=$ksPass -PcurseForgeApiKey=$curseForgeApiKey -PmodsioApiKey=$modsioApiKey --stacktrace --continue
  - cp $ORIG_ARTIFACTS .
  when: manual
  artifacts:
    name: "TickDynamic-1.12.2-$(cat $CACHE_DIR/.version)"
    paths:
    - $ARTIFACTS
